version: '3.9'
volumes:
  axon-server: {}
services:
  axon:
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      AXONIQ_AXONSERVER_NAME: axon_server
      JAVA_TOOL_OPTIONS: -Xmx512m
