server:
  port: ${APPLICATION_PORT:9000}
spring:
  application:
    name: order-service

axon:
  axonserver:
    enabled: ${AXONSERVER_ENABLED:true}
    servers: ${AXONSERVER_HOST:localhost}:${AXONSERVER_PORT:8124}