server:
  port: ${APPLICATION_PORT:9092}
spring:
  application:
    name: gojek-service

axon:
  axonserver:
    enabled: ${AXONSERVER_ENABLED:true}
    servers: ${AXONSERVER_HOST:localhost}:${AXONSERVER_PORT:8124}